<!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<!--@subject Header @-->
<!--@vars {
"var logo_height":"Email Logo Image Height",
"var logo_width":"Email Logo Image Width",
"var template_styles|raw":"Template CSS"
} @-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style type="text/css">
        {{var template_styles|raw}}

        {{css file="css/email.css"}}
    </style>
</head>
<body>
{{inlinecss file="css/email-inline.css"}}


<!-- begin logo table -->
<table align="center">
    <tr>
        <td>
            <a class="logo" href="{{store url=""}}">
            <img
                {{if logo_width}}
                width="{{var logo_width}}"
                {{else}}
                width="180"
                {{/if}}

            {{if logo_height}}
            height="{{var logo_height}}"
            {{else}}
            height="52"
            {{/if}}

            src="{{var logo_url}}"
            alt="{{var logo_alt}}"
            border="0"
            />
            </a>
        </td>
    </tr>
    </table>
<!-- end logo table -->

<!-- begin message & methods table -->
<table>
    <tr class="email-intro">
        <td>
            <h1>{{var contract_title}}</h1>
            <p>
                {{trans 'If you have questions about your order, you can email us at <a href="mailto:%store_email">%store_email</a>.' store_email=$store_email |raw}}
            </p>
        </td>
    </tr>
    <tr class="email-summary">
        <td>
            <h1>{{trans 'Your Order <span class="no-link">#%increment_id</span>' increment_id=$order.increment_id |raw}}</h1>
            <p>{{trans 'Placed on <span class="no-link">%created_at</span>' created_at=$order.getCreatedAtFormatted(1) |raw}}</p>
        </td>
    </tr>
    <tr class="email-information">
        <td>
            {{depend order.getEmailCustomerNote()}}
            <table class="message-info">
                <tr>
                    <td>
                        {{var order.getEmailCustomerNote()|escape|nl2br}}
                    </td>
                </tr>
            </table>
            {{/depend}}
            <table class="order-details">
                <tr>
                    <td class="address-details">
                        <h3>{{trans "Billing Info"}}</h3>
                        <p>{{var formattedBillingAddress|raw}}</p>
                    </td>
                    {{depend order.getIsNotVirtual()}}
                    <td class="address-details">
                        <h3>{{trans "Shipping Info"}}</h3>
                        <p>{{var formattedShippingAddress|raw}}</p>
                    </td>
                    {{/depend}}
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="method-info">
                        <h3>{{trans "Payment Method"}}</h3>
                        {{var payment_html|raw}}
                    </td>
                    {{depend order.getIsNotVirtual()}}
                    <td class="method-info">
                        <h3>{{trans "Shipping Method"}}</h3>
                        <p>{{var order.getShippingDescription()}}</p>
                    </td>
                    {{/depend}}
                </tr>
            </table>
        </td>
    </tr>
</table>
<!-- end message & methods table -->

<!-- start products & terms table -->
<table width="800">
    <tr>
        <td><br /><br />
            {{layout handle="sales_email_order_items" order=$order area="frontend"}}
        </td>
    </tr>
    <tr>
        <td>
            {{var terms|escape|nl2br}}
        </td>
    </tr>
</table>
<!-- end products & terms table -->

<!-- start signatures table -->
<table width="800">
    <tr>
        <td>
            {{depend include_manualsignature}}
            <br /><br /><br /><br />
            Signature of renter: ________________________________  &nbsp;&nbsp;&nbsp; Date: ______________________________
            <br /><br />
            {{/depend}}
            {{depend include_digitalsignature}}
            <br /><br /><br /><br />
                <tr><td width="150"><br /><br /><br /><br />Signature of renter: </td><td><img src="{{var digitalsignature}}" align="bottom"></td></tr>
                <tr><td>Date: </td><td>{{var signaturedate}}</td></tr></table>
            <br /><br />
            {{/depend}}
        </td>
    </tr>
</table>
<!-- end signatures table -->

<!-- start footer table -->
<table>
    <tr>
        <td>
            <p><a href="#">{{trans "About Us"}}</a></p>
            <p><a href="#">{{trans "Customer Service"}}</a></p>
        </td>
        <td>
            {{depend store_phone}}
            <p class="phone">
                {{trans '<a href="tel:%store_phone">%store_phone</a>' store_phone=$store_phone |raw}}
            </p>
            {{/depend}}
            {{depend store_hours}}
            <p class="hours">
                {{trans 'Hours of Operation:<br /><span class="no-link">%store_hours</span>.' store_hours=$store_hours |raw}}
            </p>
            {{/depend}}
        </td>
        <td>
            <p class="address">
                {{var store.getFormattedAddress()|raw}}
            </p>
        </td>
    </tr>
    <tr>
        <td colspan="3">{{var footertext}}</td>
    </tr>
</table>
<!-- end footer table -->

</body>
