<!--
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<!--@subject Header @-->
<!--@vars {
"var logo_height":"Email Logo Image Height",
"var logo_width":"Email Logo Image Width",
"var template_styles|raw":"Template CSS"
} @-->

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <style type="text/css">
        {
        {
            var template_styles | raw
        }
        }

        {
        {
            css file = "css/email.css"
        }
        }

        h3 {
            font-size: 20px;
        }

        body {
            color: #333333;
            font-family: 'Open Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif;
            font-style: normal;
            font-weight: 400;
            line-height: 1.42857143;
            font-size: 14px;
        }

        dl {
            margin: 0px;
            padding: 0px;
        }

        .item-info, .item-qty, .item-price {
            border-width: 1px;
            border-style: solid;
            border-color: #333333;
        }

        table.email-items {
            border-width: 1px;
            border-style: solid;
            border-color: #333333;
            width: 800px;
        }

        .basetext {
            color: #333333;
            font-size: 12px;
        }

        .toptext {
            color: #333333;
        }

        tfoot.order-totals {
            margin-top: 15px;
            text-align: right;
        }

        .bsection {
            margin-top: 20px;
        }

    </style>
    <title>{{trans 'Rental Contract'}}</title>
</head>
<body>

<!-- begin logo table -->
<table align="center">
    <tr>
        <td>
            <a class="logo" href="{{store url=""}}">
            <img
                    {{if logo_width}}
                    width="{{var logo_width}}"
                    {{else}}
                    width="180"
                    {{/if}}

            {{if logo_height}}
            height="{{var logo_height}}"
            {{else}}
            height="52"
            {{/if}}

            src="{{var logo_url}}"
            alt="{{var logo_alt}}"
            border="0"
            />
            </a>
        </td>
    </tr>
</table>
<!-- end logo table -->

<!-- begin message & methods table -->
<table>
    <tr class="email-intro">
        <td>
            <h1>{{var contract_title}}</h1>
            <p>
                {{trans 'If you have questions about your order, you can email us at <a href="mailto:%store_email">%store_email</a>.'
                store_email=$store_email |raw}}
            </p>
        </td>
    </tr>
    <tr class="email-summary">
        <td>
            <h1>{{trans 'Your Order <span class="no-link">#%increment_id</span>' increment_id=$order.increment_id |raw}}
            </h1>
            <p>{{trans 'Placed on <span class="no-link">%created_at</span>' created_at=$order.getCreatedAtFormatted(1)
                |raw}}</p>
        </td>
    </tr>
    <tr class="email-information">
        <td>
            {{depend order.getEmailCustomerNote()}}
            <table class="message-info">
                <tr>
                    <td>
                        {{var order.getEmailCustomerNote()|escape|nl2br}}
                    </td>
                </tr>
            </table>
            {{/depend}}
            <table class="order-details">
                <tr>
                    <td class="address-details">
                        <h3>{{trans "Billing Info"}}</h3>
                        <p>{{var formattedBillingAddress|raw}}</p>
                    </td>
                    {{depend order.getIsNotVirtual()}}
                    <td class="address-details">
                        <h3>{{trans "Shipping Info"}}</h3>
                        <p>{{var formattedShippingAddress|raw}}</p>
                    </td>
                    {{/depend}}
                </tr>
                <tr>
                    <td colspan="2">&nbsp;</td>
                </tr>
                <tr>
                    <td class="method-info">
                        <h3>{{trans "Payment Method"}}</h3>
                        {{var payment_html|raw}}
                    </td>
                    {{depend order.getIsNotVirtual()}}
                    <td class="method-info">
                        <h3>{{trans "Shipping Method"}}</h3>
                        <p>{{var order.getShippingDescription()}}</p>
                    </td>
                    {{/depend}}
                </tr>
            </table>
        </td>
    </tr>
</table>
<!-- end message & methods table -->

<!-- start products & terms table -->
<div class="table_order">
    {{layout handle="sales_email_order_items" order=$order area="frontend"}}
</div>
<div class="terms bsection">
    {{var terms|escape|nl2br}}
</div>
<!-- end products & terms table -->

<!-- start signatures table -->

{{depend include_manualsignature}}
<div class="signature bsection">
    <span>{{trans "Signature of renter:"}} ________________________________ </span>&nbsp;&nbsp;&nbsp; <span>{{trans "Date:"}} ______________________________</span>
</div>
{{/depend}}
{{depend include_digitalsignature}}
<div class="digital_signature bsection">
    {{trans "Signature of renter:"}} <img src="{{var digitalsignature}}" align="bottom"> {{trans "Date:"}} {{var
    signaturedate}}
</div>
{{/depend}}

<!-- end signatures table -->

<!-- start footer table -->
<div class="footer_signature bsection">
    {{var footertext}}
</div>
<!-- end footer table -->

</body>
